### ISSUE TITLE
Github Pages

### ISSUE THREAD

**Issue by mordock** [TimTerwijn/web-app-from-scratch-1920#1]
API geeft geen reactie via link Github Pages.

**Comment by SynthWeaver** [comment]
Well, the api does not work, but it did this week. I will fix it before the next feedback round

**Comment by Razpudding** [comment]
Looks like you're trying to load `App.js` when the file is actually called `app.js`

**Comment by SynthWeaver** [comment]
it still worked on my pc, but not on my github pages. I think it is because Github pages doesn't use a live server?

**Comment by SynthWeaver** [comment]
Fixed, used a relative path
