### ISSUE TITLE
Consider using promises instead of old fashioned callbacks

### ISSUE THREAD

**Issue by Razpudding** [TimTerwijn/web-app-from-scratch-1920#10]
It allows your ode to be structured in a more readable way. Now when I read your code I'm constantly jumping back and forth to see where the data goes. If you use promises you can chain asynchronous code and keep it all together.

If you're looking into promises, you should also check out async await as it allows you to wait inline for an asynchronous request to resolve. Allowing for even more readable code.

**Comment by SynthWeaver** [comment]
Lol, I just see this issue now. Sorry for asking in class today. I will fix this as said in the last issue.

**Comment by SynthWeaver** [comment]
Fixed
