### ISSUE TITLE
How to use in the readme

### ISSUE THREAD

**Issue by nlvo** [TimTerwijn/web-app-from-scratch-1920#23]
_How to use_ could use some extra information, for example:

### Installation
1. Clone or download the repository `$ git clone https://nlvo.github.io/web-app-from-scratch-1920/`
1. Install live server plugin (maybe a link?)
1. Open `index.html` in your browser

**Comment by SynthWeaver** [comment]
Thanks!, Will use this feedback

**Comment by SynthWeaver** [comment]
Fixed
